"""
PDF generator for finalised contracts.
Uses fpdf2 with HarfBuzz text shaping for proper Thai rendering.
"""

from __future__ import annotations

import logging
import os
import re
from typing import Optional

from fpdf import FPDF

from models.contract_draft import ContractArticle, PartyInfo

logger = logging.getLogger(__name__)

_ZWSP = "\u200b"
_THAI_CHAR_RE = re.compile(r"[\u0E00-\u0E7F]")

try:
    from pythainlp.tokenize import word_tokenize as _thai_word_tokenize
except Exception:
    _thai_word_tokenize = None

# ── Font paths ───────────────────────────────────────────────────────────────
_FONT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "fonts")
_FONT_REGULAR = os.path.join(_FONT_DIR, "Sarabun-Regular.ttf")
_FONT_BOLD = os.path.join(_FONT_DIR, "Sarabun-Bold.ttf")

# A4 dimensions in mm
_A4_W = 210
_A4_H = 297
_MARGIN_LEFT = 25
_MARGIN_RIGHT = 25
_MARGIN_TOP = 20
_MARGIN_BOTTOM = 20
_CONTENT_W = _A4_W - _MARGIN_LEFT - _MARGIN_RIGHT

# Thai typesetting constants
_LINE_HEIGHT = 7          # mm per line (comfortable 1.0 spacing for 14pt)
_SECTION_GAP = 4          # mm gap between articles
_HEADING_GAP_BEFORE = 6   # mm gap before article heading
_HEADING_GAP_AFTER = 1    # mm gap after article heading


class _ContractPDF(FPDF):
    """Thin subclass to add page-number footer."""

    def footer(self):
        self.set_y(-15)
        self.set_font("Sarabun", "", 9)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f"- {self.page_no()} -", align="C")


# ── Generator ────────────────────────────────────────────────────────────────


def generate_contract_pdf(
    title: str,
    preamble: str,
    articles: list[ContractArticle],
    parties: list[PartyInfo],
    effective_date: Optional[str] = None,
) -> bytes:
    """
    Generate a PDF contract document.
    Returns the PDF as bytes.
    """
    pdf = _ContractPDF()
    pdf.set_text_shaping(True)

    # Register Sarabun font
    pdf.add_font("Sarabun", "", _FONT_REGULAR)
    pdf.add_font("Sarabun", "B", _FONT_BOLD)

    pdf.set_margins(_MARGIN_LEFT, _MARGIN_TOP, _MARGIN_RIGHT)
    pdf.set_auto_page_break(True, margin=_MARGIN_BOTTOM)
    pdf.add_page()

    # ── Title ────────────────────────────────────────────────────────────
    pdf.set_font("Sarabun", "B", 18)
    pdf.multi_cell(
        w=_CONTENT_W, h=9, text=title,
        align="C", new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(3)

    if effective_date:
        pdf.set_font("Sarabun", "", 12)
        pdf.cell(
            w=_CONTENT_W, h=_LINE_HEIGHT,
            text=f"ลงวันที่ {effective_date}",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        pdf.ln(6)

    # ── Preamble ─────────────────────────────────────────────────────────
    if preamble:
        pdf.set_font("Sarabun", "", 14)
        for para_text in _iter_paragraphs(preamble):
            _write_preamble_para(pdf, para_text)
        pdf.ln(_SECTION_GAP)

    # ── Articles ─────────────────────────────────────────────────────────
    for article in articles:
        # Space before article
        pdf.ln(_HEADING_GAP_BEFORE)

        # Article heading — centered, bold
        pdf.set_font("Sarabun", "B", 14)
        heading = f"ข้อ {article.article_number}  {article.title_th}"
        pdf.multi_cell(
            w=_CONTENT_W, h=_LINE_HEIGHT, text=heading,
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        pdf.ln(_HEADING_GAP_AFTER)

        # Article body — justified with proper Thai indentation
        pdf.set_font("Sarabun", "", 14)
        body = article.body_th.strip()
        for para in _iter_paragraphs(body):
            _write_indented_para(pdf, para)
        pdf.ln(_SECTION_GAP)

    # ── Signature block ──────────────────────────────────────────────────
    pdf.ln(15)
    pdf.set_font("Sarabun", "", 14)

    col_w = _CONTENT_W / 2

    if len(parties) >= 2:
        _draw_sig_pair(pdf, col_w, parties[0], parties[1])
    elif len(parties) == 1:
        _draw_sig_single(pdf, parties[0])

    # Witness block
    pdf.ln(15)
    y_start = pdf.get_y()
    # Left witness
    pdf.set_xy(_MARGIN_LEFT, y_start)
    pdf.cell(w=col_w, text="ลงชื่อ .........................................พยาน", align="C")
    # Right witness
    pdf.set_xy(_MARGIN_LEFT + col_w, y_start)
    pdf.cell(w=col_w, text="ลงชื่อ .........................................พยาน", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    y2 = pdf.get_y()
    pdf.set_xy(_MARGIN_LEFT, y2)
    pdf.cell(w=col_w, text="( ............................................. )", align="C")
    pdf.set_xy(_MARGIN_LEFT + col_w, y2)
    pdf.cell(w=col_w, text="( ............................................. )", align="C", new_x="LMARGIN", new_y="NEXT")

    # ── Footer line ──────────────────────────────────────────────────────
    pdf.ln(15)
    pdf.set_font("Sarabun", "", 9)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(w=_CONTENT_W, text="Generated by NeoEM AI Contract Drafting Service", align="C")
    pdf.set_text_color(0, 0, 0)

    return pdf.output()


# ── Helpers ──────────────────────────────────────────────────────────────────


import re as _re

_NUMBERED_PREFIX = _re.compile(
    r"^(?:ข้อ\s*\d+|"        # ข้อ 1, ข้อ2
    r"\d+(?:\.\d+)*[\.)]?|" # 1, 1.1, 1)
    r"\([ก-ฮa-zA-Z]\)|"    # (ก) (a)
    r"[ก-ฮ][\.)])"         # ก. ก)
)


def _iter_paragraphs(text: str) -> list[str]:
    """Normalize text while preserving legal list/new-line structure."""
    if not text:
        return []
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    blocks = _re.split(r"\n\s*\n+", normalized)
    paragraphs: list[str] = []

    for block in blocks:
        lines = [part.strip() for part in block.split("\n") if part.strip()]
        if not lines:
            continue

        buffer: list[str] = []
        for line in lines:
            line = _re.sub(r"[ \t]{2,}", " ", line).strip()
            if not line:
                continue

            if _NUMBERED_PREFIX.match(line):
                if buffer:
                    paragraphs.append(" ".join(buffer).strip())
                    buffer = []
                paragraphs.append(line)
            else:
                buffer.append(line)

        if buffer:
            paragraphs.append(" ".join(buffer).strip())

    return paragraphs


def _resolve_pdf_align(text: str) -> str:
    """Use smart justify/left hybrid to reduce awkward Thai spacing."""
    spaces = text.count(" ")
    thai_chars = len(_THAI_CHAR_RE.findall(text))
    thai_ratio = thai_chars / max(len(text), 1)

    # For Thai-heavy lines with very few spaces, forced justify can stretch unnaturally.
    if thai_ratio >= 0.35 and spaces < 4:
        return "L"
    return "J"


def _inject_thai_break_opportunities(text: str) -> str:
    """Insert zero-width spaces between Thai tokens to improve wrapping."""
    if not text or _thai_word_tokenize is None:
        return text

    if len(_THAI_CHAR_RE.findall(text)) < 6:
        return text

    tokens = _thai_word_tokenize(text, keep_whitespace=True)
    if not tokens:
        return text

    out: list[str] = []
    for i, token in enumerate(tokens):
        out.append(token)
        if i == len(tokens) - 1:
            continue
        next_token = tokens[i + 1]
        if token.isspace() or next_token.isspace():
            continue
        if _THAI_CHAR_RE.search(token) and _THAI_CHAR_RE.search(next_token):
            out.append(_ZWSP)
    return "".join(out)


def _write_indented_para(pdf: FPDF, text: str):
    """Write a paragraph.
    Plain paragraphs get Thai-style ย่อหน้า first-line indent.
    Numbered/lettered sub-items (1.1, (ก), etc.) are written flush-left.
    """
    prepared = _inject_thai_break_opportunities(text)
    if _NUMBERED_PREFIX.match(text):
        # Sub-item — no indent, full content width
        pdf.multi_cell(
            w=_CONTENT_W, h=_LINE_HEIGHT, text=prepared,
            align="J", new_x="LMARGIN", new_y="NEXT",
        )
    else:
        # Body paragraph — no first-line indentation
        pdf.multi_cell(
            w=_CONTENT_W, h=_LINE_HEIGHT, text=prepared,
            align=_resolve_pdf_align(text), new_x="LMARGIN", new_y="NEXT",
        )


def _write_preamble_para(pdf: FPDF, text: str):
    """Write preamble without first-line indent and with safe justification."""
    prepared = _inject_thai_break_opportunities(text)
    pdf.multi_cell(
        w=_CONTENT_W, h=_LINE_HEIGHT, text=prepared,
        align=_resolve_pdf_align(text), new_x="LMARGIN", new_y="NEXT",
    )


def _draw_sig_pair(pdf: FPDF, col_w: float, left: PartyInfo, right: PartyInfo):
    """Draw a two-column signature block."""
    rows = [
        ("ลงชื่อ .........................................", "ลงชื่อ ........................................."),
        (f"( {left.name} )", f"( {right.name} )"),
        (left.role, right.role),
    ]
    for left_text, right_text in rows:
        y = pdf.get_y()
        pdf.set_xy(_MARGIN_LEFT, y)
        pdf.cell(w=col_w, h=_LINE_HEIGHT, text=left_text, align="C")
        pdf.set_xy(_MARGIN_LEFT + col_w, y)
        pdf.cell(w=col_w, h=_LINE_HEIGHT, text=right_text, align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)


def _draw_sig_single(pdf: FPDF, party: PartyInfo):
    """Draw a single centered signature block."""
    for text in [
        "ลงชื่อ .........................................",
        f"( {party.name} )",
        party.role,
    ]:
        pdf.cell(w=_CONTENT_W, text=text, align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
